name: Build

on:
  push:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Show Vagrant version
        run: vagrant --version
        
      - name: Init vagrant
        run: vagrant init bento/ubuntu-22.04

      - name: Run vagrant up
        run: vagrant up

      - name: Install packages
        run: vagrant ssh -c "sudo apt install -y git cgpt wget"

      - name: Setup repo
        run: vagrant ssh -c "git clone https://github.com/fkunn1326/sh1mmer"
      
     # - name: Download shim
     #   run: vagrant ssh -c "curl -OL https://mirror.the-repo.org/RMA/Shims/octopus.bin"
        
      - name: cd
        run: vagrant ssh -c "cd sh1mmer/wax"
      
      # - name: download chromebrew
      #   run: vagrant ssh -c "curl -OL https://dl.sh1mmer.me/build-tools/chromebrew/chromebrew.tar.gz"
        
      - name: build shim
        run: vagrant ssh -c "ls"
          
      - name: ls
        run: ls
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          path: octopus.bin
