name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        run: git clone -b bw-minimal https://github.com/MercuryWorkshop/sh1mmer

      - name: Install package
        run: sudo apt install -y cgpt
        
      - name: Build shim
        run: |
          cd sh1mmer/wax
          curl -OL https://mirror.the-repo.org/RMA/Shims/octopus.bin
          curl -OL https://dl.sh1mmer.me/build-tools/chromebrew/chromebrew.tar.gz
          sudo bash wax.sh octopus.bin
          
      - name: ls
        run: ls sh1mmer/wax
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          path: sh1mmer/wax/octopus.bin
