name: Build

on:
  push:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Show Vagrant version
        run: vagrant --version
        
      - name: Init vagrant
        run: vagrant init bento/ubuntu-20.04

      - name: Run vagrant up
        run: vagrant up

      - name: ssh into box after boot
        run: vagrant ssh -c "mkfs.ext2 -L arch /loop3p13"

      - name: Setup repo
        run: vagrant ssh -c "git clone https://github.com/fkunn1326/sh1mmer"
      
      - name: Download shim
        run: vagrant ssh -c "curl -OL https://mirror.the-repo.org/RMA/Shims/octopus.bin"
        
      - name: Build shim
        run: |
          cd sh1mmer/wax
          curl -OL https://dl.sh1mmer.me/build-tools/chromebrew/chromebrew.tar.gz
          sudo bash wax_macos.sh octopus.bin
          
      - name: ls
        run: ls
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          path: octopus.bin
